dist: xenial
addons:
  chrome: stable
language: python
python:
    - 3.7  
before_install:
  - python3 -V
  - pip3 install bottle
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://127.0.0.1:8000/test.html &
script:
    - python3 test/main.py 
