dist: xenial
addons:
  chrome: stable
language: python
python:
    - 3.7  
before_install:
  - python3 -V
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost/test.html &
script:
    - python3 -m http.server --directory test/ &
